import {createGuideController} from './guide-controller';
import {agedSurface} from './materials';
import * as THREE from 'three';
import {artworks,rooms,MuseumState} from './model';
export function createMuseum(host:HTMLDivElement,initial:MuseumState,onPick:(kind:string,id:string)=>void,onError:()=>void){
 const renderer=new THREE.WebGLRenderer({antialias:host.clientWidth>=800,alpha:false,powerPreference:'low-power'});renderer.setClearColor('#080b11');renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;host.appendChild(renderer.domElement);
 const scene=new THREE.Scene();scene.fog=new THREE.FogExp2('#0d1829',.026);const camera=new THREE.PerspectiveCamera(55,1,.1,150);const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let state=initial,group=new THREE.Group(),targets:THREE.Object3D[]=[],doors:THREE.Group[]=[],wheel:THREE.Group|null=null,cat:THREE.Mesh|null=null,disposed=false,frame=0,last=performance.now(),entered=performance.now(),walk=0,strafe=0,yaw=0,pitch=0,pulse=0;const keys=new Set<string>();const loader=new THREE.TextureLoader();let generation=0;const target=new THREE.Vector3();camera.position.set(0,3,32);scene.add(group);scene.add(new THREE.HemisphereLight('#7d9cff','#0b1220',1.15));const sun=new THREE.DirectionalLight('#8fa8cf',3);sun.position.set(-6,12,9);scene.add(sun);
 const effectiveQuality=()=>state.quality==='auto'?(host.clientWidth<800?'low':'standard'):state.quality;
 let lightCount=0;let upgrades:{mesh:THREE.Mesh;load:()=>void;started:boolean}[]=[];
 const materials=new Map<string,THREE.MeshStandardMaterial>();const material=(color:string,metalness=0)=>{const key=color+metalness;let m=materials.get(key);if(!m){m=agedSurface(color,metalness);materials.set(key,m);}return m;};
 function box(x:number,y:number,z:number,w:number,h:number,d:number,color:string,parent:THREE.Object3D=group){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material(color));m.position.set(x,y,z);parent.add(m);return m;}
 function pick(obj:THREE.Object3D,kind:string,id:string){obj.userData={kind,id};targets.push(obj);}
 function picture(src:string,x:number,y:number,z:number,w:number,h:number,kind:string,id:string,style='WOOD_FRAME',rot=0){
 const art=artworks.find(a=>a.id===id);if(art){w=Math.min(w,h*art.aspectRatio);h=w/art.aspectRatio;}
 const g=new THREE.Group();g.position.set(x,y,z);g.rotation.y=rot;group.add(g);
 const screen=style==='CRT'||style==='CCTV';const paper=['PHOTO','POLAROID','NEWSPAPER','MANUSCRIPT'].includes(style);
 const c=screen?'#161a20':style==='STONE_RELIEF'?'#5367ff':paper?'#d7e5ff':'#5367ff';
 box(0,0,screen?-.35:-.09,w+.25,h+.25,screen?.7:.2,c,g);
 if(style==='ORNATE_FRAME'){for(const side of [-1,1])box(side*(w/2+.15),0,0,.16,h+.5,.12,'#5367ff',g);}
 if(style==='POLAROID')box(0,-h/2-.22,0,w+.25,.4,.12,c,g);
 if(screen){box(w/2-.15,-h/2-.08,.04,.06,.035,.035,'#39d0d8',g);}
 const generationAtLoad=generation;const mat=new THREE.MeshBasicMaterial({color:'#7d9cff'});const m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),mat);m.position.z=.025;g.add(m);pick(m,kind,id);
 const valid=()=>!disposed&&generationAtLoad===generation;
 const load=(url:string,upgrade=false)=>loader.load(url,t=>{if(!valid()){t.dispose();return;}t.colorSpace=THREE.SRGBColorSpace;const previous=mat.map;mat.map=t;mat.color.set('#ffffff');mat.needsUpdate=true;previous?.dispose();},undefined,()=>{if(!valid())return;if(!upgrade&&!mat.map){mat.color.set('#17283f');onPick('asset-error',id);}});
 load(art?.thumbnail||src);
 if(art&&effectiveQuality()!=='low')upgrades.push({mesh:m,started:false,load:()=>load(art.roomSrc,true)});
 return m;
 }
 function lamp(x:number,y:number,z:number){box(x,y,z,.18,.4,.2,'#39d0d8');if(lightCount++>=(effectiveQuality()==='low'?4:effectiveQuality()==='cinematic'?16:8))return;const l=new THREE.PointLight('#39d0d8',20,12,2);l.position.set(x,y-.2,z+.5);group.add(l);}
 const guideController=createGuideController(scene,state.quality==='low'||host.clientWidth<800,onError);
 const exteriorReady=new Promise<void>((resolve,reject)=>{const image=new Image();image.onload=()=>image.decode().then(resolve,reject);image.onerror=()=>reject(new Error('Exterior unavailable'));image.src='/museum/exterior.webp';});
 const ready=Promise.all([guideController.ready,exteriorReady]);
 function free(){generation++;const geometries=new Set<THREE.BufferGeometry>(),ownedMaterials=new Set<THREE.Material>(),textures=new Set<THREE.Texture>();group.traverse(o=>{const m=o as THREE.Mesh;if(m.geometry)geometries.add(m.geometry);if(m.material)for(const mat of Array.isArray(m.material)?m.material:[m.material]){ownedMaterials.add(mat);const texture=(mat as THREE.MeshBasicMaterial).map;if(texture)textures.add(texture);}});textures.forEach(t=>t.dispose());ownedMaterials.forEach(m=>m.dispose());geometries.forEach(g=>g.dispose());materials.clear();scene.remove(group);group=new THREE.Group();scene.add(group);targets=[];doors=[];wheel=null;cat=null;upgrades=[];lightCount=0;}
 function draw(resetView=true){free();if(resetView){walk=0;strafe=0;yaw=0;pitch=0;keys.clear();}const exterior=state.phase==='outside'||state.phase==='approach'||state.phase==='welcome';const room=rooms.find(r=>r.id===state.room);const color=room?.color||'#101d32';
 box(0,-.25,0,80,.5,80,exterior?'#0b1220':'#0d1829');
 if(exterior){box(-8,6,-5,10,12,7,'#17283f');box(8,6,-5,10,12,7,'#17283f');box(0,10,-5,7,5,7,'#17283f');box(0,13,-5,29,1,9,'#17283f');for(let x=-12;x<=12;x+=4){for(const y of [4,9]){if(Math.abs(x)<3&&y===4)continue;box(x,y,-1.43,1.2,2,.1,(x+y)%3?'#0d1829':'#5367ff');}}for(const x of [-3.5,3.5])box(x,4,0,.7,8,1,'#273c67');for(let i=0;i<5;i++)box(0,.15*i,4-i*.8,9,.3,.9,'#273c67');for(let i=0;i<12;i++){const x=(i%2?1:-1)*(16+Math.sin(i)*3);box(x,5,5-i*3,.6,10,.6,'#111c2b');const crown=new THREE.Mesh(new THREE.ConeGeometry(3,8,7),material('#10233d'));crown.position.set(x,10,5-i*3);group.add(crown);}for(const side of [-1,1]){const g=new THREE.Group();g.position.set(side*3,4,0);box(-side*1.5,0,0,3,8,.3,'#0d1829',g);box(-side*.25,-.2,.22,.12,.8,.1,'#5367ff',g);group.add(g);doors.push(g);}lamp(-4,5,1);lamp(4,5,1);for(const x of [-3.4,3.4]){box(x,4,-8,.4,8,14,'#10233d');lamp(x,4,-5);lamp(x,4,-10);}box(0,8,-8,7,.3,14,'#0d1829');box(0,.025,-8,3,.04,14,'#17283f');box(0,4,-16,7,8,.3,'#0d1829');for(let i=0;i<6;i++)box(0,i*.25,-12-i*.5,4,.25,.5,'#1c2e4d');lamp(0,6,-13);}
 else {box(0,7,-12,25,14,.5,color);box(-12,6,2,.5,12,29,color);box(12,6,2,.5,12,29,color);box(0,12,1,25,.3,30,'#0e1828');for(let z=-10;z<=14;z+=3){box(0,.015,z,24,.03,.04,'#273c67');for(const x of [-11.5,11.5]){box(x,4.5,z,.4,9,.5,'#273c67');box(x,1.2,z,1,.18,2.8,'#5367ff');}}for(const x of [-8,0,8])lamp(x,8,-11);for(const z of [-6,5]){lamp(-11,5,z);lamp(11,5,z);}box(0,.035,2,4,.035,21,'#17283f');
 if(state.room==='hall'){
 for(const x of [-9,9]){box(x,5,0,.6,10,.6,'#273c67');box(x,9.6,0,1.1,.25,1.1,'#5367ff');box(x,.3,0,1.1,.6,1.1,'#172f52');}
 for(let y=2;y<11;y+=4)box(0,y,-11.5,24,.12,.2,'#5367ff');
 for(const z of [-5,4]){const hoop=new THREE.Mesh(new THREE.TorusGeometry(1.2,.08,8,24),material('#5367ff',.6));hoop.rotation.x=Math.PI/2;hoop.position.set(0,8,z);group.add(hoop);box(0,10,z,.035,4,.035,'#5367ff');for(let k=0;k<6;k++){const angle=k*Math.PI/3;lamp(Math.cos(angle)*1.2,8,Math.sin(angle)*1.2+z);}}
 for(let i=0;i<13;i++)box(0,i*.32,-4-i*.5,5,.32,.65,'#1c2e4d');box(0,4.2,-11,23,.3,2,'#182c4d');for(let x=-11;x<12;x+=.8)box(x,4.8,-10,.08,1.1,.08,'#5367ff');rooms.slice(1).forEach((r,i)=>{const x=-9+i*3;const door=box(x,2.3,-11.6,2.1,4.6,.35,r.color);pick(door,'room',r.id);lamp(x,5,-11);});cat=picture('/images/raycat/canonical-corrected.webp',0,5.5,-10,1,1,'secret','statue');const locked=box(10,2,4,2,4,.3,'#0b1220');locked.rotation.y=-Math.PI/2;pick(locked,'locked','locked');picture('/museum/rooms/49.webp',-8,4,0,2.4,3,'secret','painting','ORNATE_FRAME',Math.PI/2);}
 else{
 for(const y of [1.6,6.8,10.8])box(0,y,-11.62,24,.13,.16,'#273c67');
 if(state.room==='ancient'){for(const x of [-10,10]){const column=new THREE.Mesh(new THREE.CylinderGeometry(.4,.55,5,16),material('#5367ff'));column.position.set(x,2.5,-6);group.add(column);box(x,.2,-6,1.4,.4,1.4,'#5367ff');box(x,5,-6,1.2,.35,1.2,'#5367ff');}box(0,.6,1,4,1.2,2,'#263b61');}
 if(state.room==='old-world'){box(0,1.2,0,4,.15,2,'#182c4d');for(const x of [-1.7,1.7])box(x,.6,0,.2,1.2,1.7,'#0b1220');const globe=new THREE.Mesh(new THREE.SphereGeometry(.65,24,16),material('#273c67'));globe.position.set(1,1.95,0);group.add(globe);box(-1,1.4,0,1,.25,.7,'#7d9cff');}
 if(state.room==='golden-age'){box(0,.7,1,5,.6,1.5,'#172f52');for(const x of [-2,2])box(x,.3,1,.2,.6,1,'#5367ff');}
 if(state.room==='modern'){for(const x of [-8,8])box(x,.9,3,1.8,1.8,1.8,'#182c4d');}
 const list=state.room==='secret'?artworks.filter(a=>[20,49,50].includes(a.order)):artworks.filter(a=>a.room===state.room);const batch=list.slice(state.page*6,state.page*6+6);batch.forEach((a,i)=>{const ratio=a.aspectRatio;const w=Math.min(5.2,4.4*ratio),h=w/ratio;const back=i<3;picture(effectiveQuality()==='low'?a.thumbnail:a.roomSrc,back?-7+i*7:(i===3?-11.6:11.6),4,back?-11.65:(i===5?4:-4),w,h,'art',a.id,a.displayType,back?0:(i===3?Math.PI/2:-Math.PI/2));});if(state.room==='archive'){for(const x of [-8,8])for(let i=0;i<4;i++){const drawer=box(x,1+i*.48,2,3,.42,1.2,'#10233d');pick(drawer,'drawer',String(i));box(x,1+i*.48,2.63,.7,.07,.06,'#5367ff');}}if(state.room==='money'){wheel=new THREE.Group();wheel.position.set(0,3,0);const rim=new THREE.Mesh(new THREE.TorusGeometry(2.1,.17,10,48),material('#5367ff',.65));wheel.add(rim);for(let i=0;i<8;i++){const spoke=box(0,0,0,.09,4,.1,'#7d9cff',wheel);spoke.rotation.z=i*Math.PI/4;}group.add(wheel);pick(rim,'wheel','wheel');box(0,.4,0,4.8,.8,1.8,'#17283f');}if(state.room==='digital'){box(0,1,1,3,2,1.5,'#151922');picture('/museum/thumbs/16.webp',0,2.3,1.8,2,1.5,'art','016','CCTV');}if(state.room==='secret'){for(let i=0;i<5;i++)box(-5+i*2.5,.6,1,1.8,1.2,1,'#1c2e4d');} }
 }
 }
 draw();function resize(){renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();const q=effectiveQuality();renderer.setPixelRatio(q==='low'?1:q==='cinematic'?Math.min(devicePixelRatio,2):Math.min(devicePixelRatio,1.4));}const observer=new ResizeObserver(resize);observer.observe(host);resize();
 let activeGuide='';
 function tick(now:number){if(disposed||document.hidden)return;const dt=Math.min((now-last)/1000,.05);last=now;const elapsed=(now-entered)/1000;const outdoor=['outside','approach','welcome'].includes(state.phase);let z=outdoor?state.reduced?5:state.phase==='outside'?32:state.phase==='approach'?Math.max(5,32-elapsed*5):5-Math.max(0,elapsed-4.6)*2:12;
 if(!outdoor&&!state.focus){if(keys.has('w')||keys.has('arrowup'))walk+=dt*2;if(keys.has('s')||keys.has('arrowdown'))walk-=dt*2;if(state.mode==='explore'){if(keys.has('a'))strafe-=dt*2;if(keys.has('d'))strafe+=dt*2;strafe=THREE.MathUtils.clamp(strafe,-9,9);}walk=THREE.MathUtils.clamp(walk,-2,16);}if(!outdoor)z-=walk;
 target.set(state.mode==='explore'?strafe:Math.sin(yaw)*.7,outdoor?3:3.1,z);camera.position.lerp(target,state.reduced?1:1-Math.exp(-dt*3));camera.lookAt(camera.position.x+Math.sin(yaw)*7,3.1+pitch,camera.position.z-10);doors.forEach((g,i)=>g.rotation.y=(state.phase==='welcome'?(state.reduced?1.4:Math.min(1.4,elapsed)):0)*(i===0?-1:1));if(cat&&state.phase==='welcome')cat.visible=true;guideController.update(dt,state,camera);if(wheel&&!state.reduced)wheel.rotation.z+=dt*(pulse>now?1.4:.035);if(!outdoor&&state.guide&&!state.focus){const hit=targets.filter(o=>o.userData.kind==='art').sort((a,b)=>camera.position.distanceToSquared(a.getWorldPosition(new THREE.Vector3()))-camera.position.distanceToSquared(b.getWorldPosition(new THREE.Vector3()))).find(o=>o.userData.kind==='art'&&artworks.find(a=>a.id===o.userData.id)?.guide&&(()=>{const point=o.getWorldPosition(new THREE.Vector3());return Math.hypot(point.x-camera.position.x,point.z-camera.position.z)<(artworks.find(a=>a.id===o.userData.id)?.guide?.triggerRadius??9);})());const id=hit?.userData.id||'';if(id!==activeGuide){activeGuide=id;onPick(id?'guide':'guide-leave',id);}}else if(activeGuide&&!state.focus){activeGuide='';onPick('guide-leave','');}for(const asset of upgrades){if(!asset.started&&camera.position.distanceTo(asset.mesh.getWorldPosition(new THREE.Vector3()))<16){asset.started=true;asset.load();}}renderer.render(scene,camera);if(process.env.NODE_ENV!=='production'){host.dataset.textures=String(renderer.info.memory.textures);host.dataset.geometries=String(renderer.info.memory.geometries);host.dataset.cameraZ=camera.position.z.toFixed(3);}frame=requestAnimationFrame(tick);}
 frame=requestAnimationFrame(tick);const keydown=(e:KeyboardEvent)=>{if(state.focus||(e.target as HTMLElement)?.closest('input,select,textarea,button,a,[contenteditable=true]'))return;if(['ArrowUp','ArrowDown'].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase());},keyup=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase());const scroll=(e:WheelEvent)=>{if(state.focus||state.phase!=='inside')return;walk=THREE.MathUtils.clamp(walk+e.deltaY*.006,-2,16);};let drag=false,px=0,py=0,moved=0;const down=(e:PointerEvent)=>{if(state.focus||state.phase!=='inside')return;drag=true;px=e.clientX;py=e.clientY;moved=0;};const move=(e:PointerEvent)=>{if(!drag||state.focus)return;const dx=e.clientX-px,dy=e.clientY-py;moved+=Math.abs(dx)+Math.abs(dy);yaw-=dx*.003;pitch=THREE.MathUtils.clamp(pitch+dy*.005,-1.3,1.3);if(e.pointerType==='touch')walk=THREE.MathUtils.clamp(walk-dy*.025,-2,16);px=e.clientX;py=e.clientY;};const up=(e:PointerEvent)=>{const wasDragging=drag;drag=false;if(!wasDragging||state.focus||e.target!==renderer.domElement||moved>8)return;const b=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(targets)[0];if(hit){if(hit.object.userData.kind==='wheel')pulse=performance.now()+5000;onPick(hit.object.userData.kind,hit.object.userData.id);}};window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);renderer.domElement.addEventListener('wheel',scroll,{passive:true});renderer.domElement.addEventListener('pointerdown',down);window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);const clearInput=()=>{keys.clear();drag=false;};const visibility=()=>{clearInput();cancelAnimationFrame(frame);if(!document.hidden){last=performance.now();frame=requestAnimationFrame(tick);}};window.addEventListener('blur',clearInput);window.addEventListener('pointercancel',clearInput);document.addEventListener('visibilitychange',visibility);const lost=(e:Event)=>{e.preventDefault();onError();};renderer.domElement.addEventListener('webglcontextlost',lost);
 return {ready,reset(){walk=0;strafe=0;yaw=0;pitch=0;keys.clear();},update(next:MuseumState){const redraw=next.room!==state.room||next.page!==state.page||next.quality!==state.quality||(['outside','approach','welcome'].includes(next.phase)!==['outside','approach','welcome'].includes(state.phase));if(next.phase!==state.phase)entered=performance.now();const moved=next.room!==state.room||next.page!==state.page||next.phase!==state.phase;if(next.focus)clearInput();state=next;if(redraw)draw(moved);resize();},dispose(){disposed=true;cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener('blur',clearInput);window.removeEventListener('pointercancel',clearInput);document.removeEventListener('visibilitychange',visibility);window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);renderer.domElement.removeEventListener('pointerdown',down);renderer.domElement.removeEventListener('wheel',scroll);renderer.domElement.removeEventListener('webglcontextlost',lost);free();guideController.dispose();renderer.dispose();renderer.domElement.remove();}};
}
