import {createRoomGuide} from './room-guide';
import {welcomeRayCat} from './welcome-raycat';
import {agedSurface} from './materials';
import * as THREE from 'three';
import {artworks,rooms,MuseumState} from './model';
export function createMuseum(host:HTMLDivElement,initial:MuseumState,onPick:(kind:string,id:string)=>void,onError:()=>void){
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'low-power'});renderer.setClearColor('#080b11');renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;host.appendChild(renderer.domElement);
 const scene=new THREE.Scene();scene.fog=new THREE.FogExp2('#111219',.026);const camera=new THREE.PerspectiveCamera(55,1,.1,150);const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let state=initial,group=new THREE.Group(),targets:THREE.Object3D[]=[],doors:THREE.Group[]=[],wheel:THREE.Group|null=null,cat:THREE.Mesh|null=null,disposed=false,frame=0,last=performance.now(),entered=performance.now(),walk=0,strafe=0,yaw=0,pitch=0,pulse=0;const keys=new Set<string>();const loader=new THREE.TextureLoader();let generation=0;const target=new THREE.Vector3();camera.position.set(0,3,32);scene.add(group);scene.add(new THREE.HemisphereLight('#a8b9d8','#3c2414',1.15));const sun=new THREE.DirectionalLight('#e9c394',3);sun.position.set(-6,12,9);scene.add(sun);
 const materials=new Map<string,THREE.MeshStandardMaterial>();const material=(color:string,metalness=0)=>{const key=color+metalness;let m=materials.get(key);if(!m){m=agedSurface(color,metalness);materials.set(key,m);}return m;};
 function box(x:number,y:number,z:number,w:number,h:number,d:number,color:string,parent:THREE.Object3D=group){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material(color));m.position.set(x,y,z);parent.add(m);return m;}
 function pick(obj:THREE.Object3D,kind:string,id:string){obj.userData={kind,id};targets.push(obj);}
 function picture(src:string,x:number,y:number,z:number,w:number,h:number,kind:string,id:string,style='WOOD_FRAME',rot=0){const g=new THREE.Group();g.position.set(x,y,z);g.rotation.y=rot;group.add(g);const c=style==='CRT'||style==='CCTV'?'#161a20':style==='STONE_RELIEF'?'#827363':style==='PHOTO'||style==='POLAROID'?'#c8bca5':'#8a683b';box(0,0,-.09,w+.25,h+.25,.2,c,g);const generationAtLoad=generation;const mat=new THREE.MeshBasicMaterial({color:'#8e8271'});const m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),mat);m.position.z=.025;g.add(m);pick(m,kind,id);loader.load(src,t=>{if(disposed||generationAtLoad!==generation){t.dispose();return;}t.colorSpace=THREE.SRGBColorSpace;mat.map=t;mat.color.set('#ffffff');mat.needsUpdate=true;},undefined,()=>{mat.color.set('#483f35')});return m;}
 function lamp(x:number,y:number,z:number){box(x,y,z,.18,.4,.2,'#caa468');const l=new THREE.PointLight('#efb568',20,12,2);l.position.set(x,y-.2,z+.5);group.add(l);}
 let roomGuide:ReturnType<typeof createRoomGuide>|null=null;
 let owner:ReturnType<typeof welcomeRayCat>|null=null;
 function free(){roomGuide?.dispose();roomGuide=null;owner?.dispose();owner=null;generation++;group.traverse(o=>{const m=o as THREE.Mesh;if(m.geometry)m.geometry.dispose();if(m.material){for(const mat of Array.isArray(m.material)?m.material:[m.material]){const t=(mat as THREE.MeshBasicMaterial).map;if(t)t.dispose();mat.dispose();}}});materials.clear();scene.remove(group);group=new THREE.Group();scene.add(group);targets=[];doors=[];wheel=null;cat=null;}
 function draw(){free();walk=0;strafe=0;yaw=0;const exterior=state.phase==='outside'||state.phase==='approach'||state.phase==='welcome';const room=rooms.find(r=>r.id===state.room);const color=room?.color||'#382e22';
 box(0,-.25,0,80,.5,80,exterior?'#101b19':'#32251c');
 if(exterior){box(-8,6,-5,10,12,7,'#434039');box(8,6,-5,10,12,7,'#434039');box(0,10,-5,7,5,7,'#434039');box(0,13,-5,29,1,9,'#272b30');for(let x=-12;x<=12;x+=4){for(const y of [4,9]){if(Math.abs(x)<3&&y===4)continue;box(x,y,-1.43,1.2,2,.1,(x+y)%3?'#131a25':'#b88c52');}}for(const x of [-3.5,3.5])box(x,4,0,.7,8,1,'#6a6050');for(let i=0;i<5;i++)box(0,.15*i,4-i*.8,9,.3,.9,'#5c584d');for(let i=0;i<12;i++){const x=(i%2?1:-1)*(16+Math.sin(i)*3);box(x,5,5-i*3,.6,10,.6,'#252823');const crown=new THREE.Mesh(new THREE.ConeGeometry(3,8,7),material('#172722'));crown.position.set(x,10,5-i*3);group.add(crown);}for(const side of [-1,1]){const g=new THREE.Group();g.position.set(side*3,4,0);box(-side*1.5,0,0,3,8,.3,'#302016',g);box(-side*.25,-.2,.22,.12,.8,.1,'#ad8246',g);group.add(g);doors.push(g);}lamp(-4,5,1);lamp(4,5,1);owner=welcomeRayCat(group,state.quality==='low'||host.clientWidth<800);for(const x of [-3.4,3.4]){box(x,4,-8,.4,8,14,'#30241c');lamp(x,4,-5);lamp(x,4,-10);}box(0,8,-8,7,.3,14,'#211a15');box(0,.025,-8,3,.04,14,'#49302b');box(0,4,-16,7,8,.3,'#241c17');for(let i=0;i<6;i++)box(0,i*.25,-12-i*.5,4,.25,.5,'#66513b');lamp(0,6,-13);}
 else {roomGuide=createRoomGuide(group,state.room,state.page,state.quality==='low'||host.clientWidth<800);box(0,7,-12,25,14,.5,color);box(-12,6,2,.5,12,29,color);box(12,6,2,.5,12,29,color);box(0,12,1,25,.3,30,'#211c18');for(let z=-10;z<=14;z+=3){box(0,.015,z,24,.03,.04,'#66533a');for(const x of [-11.5,11.5]){box(x,4.5,z,.4,9,.5,'#493d30');box(x,1.2,z,1,.18,2.8,'#80613f');}}for(const x of [-8,0,8])lamp(x,8,-11);for(const z of [-6,5]){lamp(-11,5,z);lamp(11,5,z);}box(0,.035,2,4,.035,21,'#49302b');
 if(state.room==='hall'){
 for(const x of [-9,9]){box(x,5,0,.6,10,.6,'#62523f');box(x,9.6,0,1.1,.25,1.1,'#aa895e');box(x,.3,0,1.1,.6,1.1,'#5f503d');}
 for(let y=2;y<11;y+=4)box(0,y,-11.5,24,.12,.2,'#9b7b52');
 for(const z of [-5,4]){const hoop=new THREE.Mesh(new THREE.TorusGeometry(1.2,.08,8,24),material('#9d7b48',.6));hoop.rotation.x=Math.PI/2;hoop.position.set(0,8,z);group.add(hoop);box(0,10,z,.035,4,.035,'#7d6545');for(let k=0;k<6;k++){const angle=k*Math.PI/3;lamp(Math.cos(angle)*1.2,8,Math.sin(angle)*1.2+z);}}
 for(let i=0;i<13;i++)box(0,i*.32,-4-i*.5,5,.32,.65,'#66513b');box(0,4.2,-11,23,.3,2,'#6d5238');for(let x=-11;x<12;x+=.8)box(x,4.8,-10,.08,1.1,.08,'#ae8853');rooms.slice(1).forEach((r,i)=>{const x=-9+i*3;const door=box(x,2.3,-11.6,2.1,4.6,.35,r.color);pick(door,'room',r.id);lamp(x,5,-11);});cat=picture('/images/raycat/canonical-corrected.webp',0,5.5,-10,1,1,'secret','statue');const locked=box(10,2,4,2,4,.3,'#221b17');locked.rotation.y=-Math.PI/2;pick(locked,'locked','locked');picture('/museum/rooms/49.webp',-8,4,0,2.4,3,'secret','painting','ORNATE_FRAME',Math.PI/2);}
 else{
 for(const y of [1.6,6.8,10.8])box(0,y,-11.62,24,.13,.16,'#786040');
 if(state.room==='ancient'){for(const x of [-10,10]){const column=new THREE.Mesh(new THREE.CylinderGeometry(.4,.55,5,16),material('#7f7058'));column.position.set(x,2.5,-6);group.add(column);box(x,.2,-6,1.4,.4,1.4,'#847257');box(x,5,-6,1.2,.35,1.2,'#847257');}box(0,.6,1,4,1.2,2,'#716451');}
 if(state.room==='old-world'){box(0,1.2,0,4,.15,2,'#593d26');for(const x of [-1.7,1.7])box(x,.6,0,.2,1.2,1.7,'#332315');const globe=new THREE.Mesh(new THREE.SphereGeometry(.65,24,16),material('#657264'));globe.position.set(1,1.95,0);group.add(globe);box(-1,1.4,0,1,.25,.7,'#9b8160');}
 if(state.room==='golden-age'){box(0,.7,1,5,.6,1.5,'#55372e');for(const x of [-2,2])box(x,.3,1,.2,.6,1,'#95754a');}
 if(state.room==='modern'){for(const x of [-8,8])box(x,.9,3,1.8,1.8,1.8,'#4c4439');}
 const list=state.room==='secret'?artworks.filter(a=>[20,49,50].includes(a.order)):artworks.filter(a=>a.room===state.room);const batch=list.slice(state.page*6,state.page*6+6);batch.forEach((a,i)=>{const ratio=a.aspectRatio;const h=4.4,w=Math.min(5.2,h*ratio);const back=i<3;picture(state.quality==='low'?a.thumbnail:a.roomSrc,back?-7+i*7:(i===3?-11.6:11.6),4,back?-11.65:(i===5?4:-4),w,h,'art',a.id,a.displayType,back?0:(i===3?Math.PI/2:-Math.PI/2));});if(state.room==='archive'){for(const x of [-8,8])for(let i=0;i<4;i++){const drawer=box(x,1+i*.48,2,3,.42,1.2,'#4a3527');pick(drawer,'drawer',String(i));box(x,1+i*.48,2.63,.7,.07,.06,'#b78a4a');}}if(state.room==='money'){wheel=new THREE.Group();wheel.position.set(0,3,0);const rim=new THREE.Mesh(new THREE.TorusGeometry(2.1,.17,10,48),material('#98784c',.65));wheel.add(rim);for(let i=0;i<8;i++){const spoke=box(0,0,0,.09,4,.1,'#7d715e',wheel);spoke.rotation.z=i*Math.PI/4;}group.add(wheel);pick(rim,'wheel','wheel');box(0,.4,0,4.8,.8,1.8,'#323331');}if(state.room==='digital'){box(0,1,1,3,2,1.5,'#151922');picture('/museum/thumbs/16.webp',0,2.3,1.8,2,1.5,'art','016','CCTV');}if(state.room==='secret'){for(let i=0;i<5;i++)box(-5+i*2.5,.6,1,1.8,1.2,1,'#61472d');} }
 }
 }
 draw();function resize(){renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();const q=state.quality==='auto'?(window.innerWidth<800?'low':'standard'):state.quality;renderer.setPixelRatio(q==='low'?1:q==='cinematic'?Math.min(devicePixelRatio,2):Math.min(devicePixelRatio,1.4));}const observer=new ResizeObserver(resize);observer.observe(host);resize();
 let activeGuide='';
 function tick(now:number){if(disposed)return;const dt=Math.min((now-last)/1000,.05);last=now;const elapsed=(now-entered)/1000;const outdoor=['outside','approach','welcome'].includes(state.phase);let z=outdoor?state.phase==='outside'?32:state.phase==='approach'?Math.max(5,32-elapsed*5):5-Math.max(0,elapsed-4.6)*2:12;
 if(!outdoor&&!state.focus){if(keys.has('w')||keys.has('ArrowUp'))walk+=dt*2;if(keys.has('s')||keys.has('ArrowDown'))walk-=dt*2;if(state.mode==='explore'){if(keys.has('a'))strafe-=dt*2;if(keys.has('d'))strafe+=dt*2;strafe=THREE.MathUtils.clamp(strafe,-9,9);}walk=THREE.MathUtils.clamp(walk,-2,16);z-=walk;}
 target.set(state.mode==='explore'?strafe:Math.sin(yaw)*.7,outdoor?3:3.1,z);camera.position.lerp(target,state.reduced?1:1-Math.exp(-dt*3));camera.lookAt(camera.position.x+Math.sin(yaw)*7,3.1+pitch,camera.position.z-10);doors.forEach((g,i)=>g.rotation.y=(state.phase==='welcome'?Math.min(1.4,elapsed):0)*(i===0?-1:1));if(cat&&state.phase==='welcome')cat.visible=true;if(owner)owner.update(state.phase==='welcome'?elapsed:0,state.reduced);roomGuide?.update(dt,state.guide,state.reduced);if(wheel&&!state.reduced)wheel.rotation.z+=dt*(pulse>now?1.4:.035);if(!outdoor&&state.guide&&!state.focus){const hit=targets.find(o=>o.userData.kind==='art'&&artworks.find(a=>a.id===o.userData.id)?.guide&&(()=>{const point=o.getWorldPosition(new THREE.Vector3());return Math.hypot(point.x-camera.position.x,point.z-camera.position.z)<(artworks.find(a=>a.id===o.userData.id)?.guide?.triggerRadius??9);})());const id=hit?.userData.id||'';if(id!==activeGuide){activeGuide=id;onPick(id?'guide':'guide-leave',id);}}else if(activeGuide){activeGuide='';onPick('guide-leave','');}renderer.render(scene,camera);frame=requestAnimationFrame(tick);}
 frame=requestAnimationFrame(tick);const keydown=(e:KeyboardEvent)=>{if(state.focus||(e.target as HTMLElement)?.matches('input,select,button,a'))return;if(['ArrowUp','ArrowDown'].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase());},keyup=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase());const scroll=(e:WheelEvent)=>{if(state.focus)return;walk=THREE.MathUtils.clamp(walk+e.deltaY*.006,-2,16);};let drag=false,px=0,py=0,moved=0;const down=(e:PointerEvent)=>{drag=true;px=e.clientX;py=e.clientY;moved=0;};const move=(e:PointerEvent)=>{if(!drag)return;const dx=e.clientX-px,dy=e.clientY-py;moved+=Math.abs(dx)+Math.abs(dy);yaw=THREE.MathUtils.clamp(yaw-dx*.003,-.8,.8);pitch=THREE.MathUtils.clamp(pitch+dy*.005,-1.3,1.3);if(e.pointerType==='touch')walk=THREE.MathUtils.clamp(walk-dy*.025,-2,16);px=e.clientX;py=e.clientY;};const up=(e:PointerEvent)=>{const wasDragging=drag;drag=false;if(!wasDragging||state.focus||e.target!==renderer.domElement||moved>8)return;const b=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(targets)[0];if(hit){if(hit.object.userData.kind==='wheel')pulse=performance.now()+5000;onPick(hit.object.userData.kind,hit.object.userData.id);}};window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);renderer.domElement.addEventListener('wheel',scroll,{passive:true});renderer.domElement.addEventListener('pointerdown',down);window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);const lost=(e:Event)=>{e.preventDefault();onError();};renderer.domElement.addEventListener('webglcontextlost',lost);
 return {reset(){walk=0;strafe=0;yaw=0;pitch=0;keys.clear();},update(next:MuseumState){const redraw=next.room!==state.room||next.page!==state.page||next.quality!==state.quality||(['outside','approach','welcome'].includes(next.phase)!==['outside','approach','welcome'].includes(state.phase));if(next.phase!==state.phase)entered=performance.now();state=next;if(redraw)draw();resize();},dispose(){disposed=true;cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);renderer.domElement.removeEventListener('pointerdown',down);renderer.domElement.removeEventListener('wheel',scroll);renderer.domElement.removeEventListener('webglcontextlost',lost);free();renderer.dispose();renderer.domElement.remove();}};
}
