'use client';
import RayCatDialogue from './RayCatDialogue';
import ArtworkImage from './ArtworkImage';
import {prefetchWall} from './assets';
import './guide.css';

import {useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import Navigation from './Navigation';
import './navigation.css';
import {artworks,rooms,Artwork,MuseumState} from './model';
import './museum.css';

type RoomVoice={oscillators:OscillatorNode[];gain:GainNode;filter:BiquadFilterNode};
const ROOM_SOUND:{[key:string]:{base:number;drift:number;wave:OscillatorType;filter:number}}={
 hall:{base:110,drift:2,wave:'sine',filter:900}, ancient:{base:73,drift:1.5,wave:'triangle',filter:520}, 'old-world':{base:146.83,drift:2.5,wave:'sine',filter:760}, 'golden-age':{base:196,drift:3,wave:'triangle',filter:1200}, money:{base:98,drift:4,wave:'sine',filter:680}, digital:{base:220,drift:7,wave:'sine',filter:1800}, modern:{base:164.81,drift:5,wave:'triangle',filter:1400}, archive:{base:82.41,drift:1,wave:'sine',filter:430}, secret:{base:55,drift:.8,wave:'triangle',filter:360}
};

export default function Museum(){
 const panel=useRef<HTMLElement>(null);
 const restoreRoute=useRef<()=>void>(()=>{});
 const host=useRef<HTMLDivElement>(null),engine=useRef<ReturnType<typeof import('./engine').createMuseum>|null>(null),dialog=useRef<HTMLDialogElement>(null),audio=useRef<AudioContext|null>(null),voice=useRef<RoomVoice|null>(null);
 const [room,setRoom]=useState('hall'),[phase,setPhase]=useState('outside'),[mode,setMode]=useState('guided'),[quality,setQuality]=useState('auto'),[reduced,setReduced]=useState(false),[fallback,setFallback]=useState(false),[ready,setReady]=useState(false),[page,setPage]=useState(0),[focus,setFocus]=useState<Artwork|null>(null),[menu,setMenu]=useState(''),[search,setSearch]=useState(''),[seen,setSeen]=useState<string[]>([]),[sound,setSound]=useState(false),[secret,setSecret]=useState(0),[notice,setNotice]=useState('');
 const [activeArtwork,setActiveArtwork]=useState('');
 const [guide,setGuide]=useState(true),[dialogue,setDialogue]=useState<Artwork|null>(null);const spoken=useRef(new Set<string>());
 function tell(id:string){setActiveArtwork(id);const art=artworks.find(a=>a.id===id);if(!guide||!art?.guide||spoken.current.has(id))return;spoken.current.add(id);setDialogue(art);}
 const [viewVersion,setViewVersion]=useState(0);
 const list=room==='secret'?artworks.filter(a=>[20,49,50].includes(a.order)):artworks.filter(a=>a.room===room);const pages=Math.max(1,Math.ceil(list.length/6));
 const state:MuseumState={guide,room,phase,mode,quality,reduced,focus:!!focus||!!menu,page,activeArtwork:focus?.id||activeArtwork};const stateRef=useRef(state);stateRef.current=state;
 const actions=useRef<(kind:string,id:string)=>void>(()=>{});
 function route(query:string){const url=new URL(location.href);url.searchParams.delete('room');url.searchParams.delete('art');url.searchParams.delete('wall');new URLSearchParams(query).forEach((v,k)=>url.searchParams.set(k,v));if(url.href!==location.href)history.pushState(null,'',url);}
 function visit(id:string,write=true,wall=0){setActiveArtwork('');setDialogue(null);setViewVersion(v=>v+1);setRoom(id);setPage(Math.max(0,Math.min(wall,Math.ceil(artworks.filter(a=>a.room===id).length/6)-1)));setPhase('inside');setMenu('');setFocus(null);if(write)route(`room=${id}`);}
 function inspect(art:Artwork,write=true){setActiveArtwork(art.id);setDialogue(guide&&art.guide?art:null);setRoom(art.room);setPhase('inside');setFocus(art);setPage(Math.floor(artworks.filter(a=>a.room===art.room).findIndex(a=>a.id===art.id)/6));setSeen(s=>s.includes(art.id)?s:[...s,art.id]);setMenu('');if(write)route(`art=${art.id}`);}
 function closeFocus(){setFocus(null);route(`room=${room}&wall=${page}`);}
 actions.current=(kind,id)=>{if(kind==='guide')tell(id);if(kind==='guide-leave'&&!stateRef.current.focus){setDialogue(null);setActiveArtwork('');}if(kind==='art'){tell(id);const a=artworks.find(a=>a.id===id);if(a)inspect(a);}if(kind==='room')visit(id);if(kind==='secret')setSecret(s=>s+1);if(kind==='locked')setNotice('NOT YET.');if(kind==='drawer')setPage(p=>(p+1)%pages);if(kind==='wheel')setNotice('THE MECHANISM WAKES.');};
 restoreRoute.current=()=>{const params=new URLSearchParams(location.search);const art=artworks.find(a=>a.id===params.get('art'));if(art)inspect(art,false);else if(rooms.some(r=>r.id===params.get('room'))||params.get('room')==='secret')visit(params.get('room')!,false,Number(params.get('wall'))||0);else if(params.has('art')||params.has('room')){visit('hall',false);setNotice('Sighting not found. Welcome to the Grand Hall.');}else {setFocus(null);setMenu('');setPhase('outside');setRoom('hall');setPage(0);}if(params.get('fallback')==='1')setFallback(true);};
 useEffect(()=>{const mq=matchMedia('(prefers-reduced-motion: reduce)');setReduced(mq.matches);const change=()=>setReduced(mq.matches);mq.addEventListener('change',change);restoreRoute.current();const pop=()=>restoreRoute.current();window.addEventListener('popstate',pop);try{const saved=sessionStorage.getItem('raycat-museum-seen');if(saved){const ids=JSON.parse(saved);if(Array.isArray(ids))setSeen(current=>[...new Set([...current,...ids.filter(id=>artworks.some(a=>a.id===id))])]);}}catch{}return()=>{mq.removeEventListener('change',change);window.removeEventListener('popstate',pop);};},[]);
 useEffect(()=>{if(!menu||!panel.current)return;const element=panel.current;const previous=document.activeElement as HTMLElement;const siblings=Array.from(element.parentElement!.children).filter(el=>el!==element&&!el.classList.contains('museum-panel-scrim')) as HTMLElement[];siblings.forEach(el=>el.inert=true);const controls=()=>Array.from(element.querySelectorAll<HTMLElement>('button,input,select,a[href]')).filter(el=>!el.hasAttribute('disabled'));controls()[0]?.focus();const trap=(e:KeyboardEvent)=>{if(e.key!=='Tab')return;const items=controls(),first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}};element.addEventListener('keydown',trap);return()=>{siblings.forEach(el=>el.inert=false);element.removeEventListener('keydown',trap);if(previous?.isConnected&&!dialog.current?.open)previous.focus();};},[menu]);
 useEffect(()=>{if(fallback){setReady(true);return;}setReady(false);let cancelled=false;import('./engine').then(({createMuseum})=>{if(cancelled||!host.current)return;try{engine.current=createMuseum(host.current,stateRef.current,(k,id)=>actions.current(k,id),()=>setFallback(true));const current=engine.current;let timeout:ReturnType<typeof setTimeout>;Promise.race([current.ready,new Promise((_,reject)=>{timeout=setTimeout(()=>reject(new Error('Asset timeout')),15000);})]).then(()=>{if(!cancelled)setReady(true);}).catch(()=>{if(!cancelled){setNotice('3D assets unavailable. Accessible museum enabled.');setFallback(true);}}).finally(()=>clearTimeout(timeout));}catch{setFallback(true);setReady(true);}}).catch(()=>{setFallback(true);setReady(true)});return()=>{cancelled=true;engine.current?.dispose();engine.current=null;};},[fallback]);
 useEffect(()=>{engine.current?.update(state);},[room,phase,mode,quality,reduced,focus,menu,page,guide,activeArtwork]);
 useEffect(()=>{if(ready&&phase==='outside'){const timer=setTimeout(()=>setPhase('approach'),reduced?100:650);return()=>clearTimeout(timer);}},[ready,phase,reduced]);
 useEffect(()=>{if(phase==='approach'){const t=setTimeout(()=>setPhase('welcome'),reduced?100:5200);return()=>clearTimeout(t);}if(phase==='welcome'){const t=setTimeout(()=>setPhase('inside'),reduced?3200:7000);return()=>clearTimeout(t);}},[phase,reduced]);
 useEffect(()=>{if(secret>=3){visit('secret');setNotice('THE HOUSE REMEMBERS.');setSecret(0);}},[secret]);
 useEffect(()=>{if(notice){const t=setTimeout(()=>setNotice(''),2800);return()=>clearTimeout(t);}},[notice]);
 useEffect(()=>{if(focus&&!dialog.current?.open)dialog.current?.showModal();if(!focus&&dialog.current?.open)dialog.current.close();},[focus]);
 useEffect(()=>()=>{voice.current?.oscillators.forEach(node=>node.stop());audio.current?.close();},[]);
 useEffect(()=>{try{if(seen.length)sessionStorage.setItem('raycat-museum-seen',JSON.stringify(seen));}catch{}},[seen]);
 useEffect(()=>{const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setMenu('');};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape);},[]);
  function startRoomVoice(nextRoom:string,immediate=false){
  const ctx=audio.current;if(!ctx)return;const profile=ROOM_SOUND[nextRoom]||ROOM_SOUND.hall;
  const nextGain=ctx.createGain(),filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=profile.filter;filter.Q.value=.7;
  nextGain.gain.setValueAtTime(immediate?.014:0,ctx.currentTime);nextGain.gain.linearRampToValueAtTime(.014,ctx.currentTime+(immediate?.05:1.8));filter.connect(nextGain);nextGain.connect(ctx.destination);
  const oscillators=[profile.base,profile.base*1.5].map((frequency,index)=>{const node=ctx.createOscillator();node.type=profile.wave;node.frequency.value=frequency;node.detune.value=index?profile.drift:-profile.drift;node.connect(filter);node.start();return node;});
  const previous=voice.current;voice.current={oscillators,gain:nextGain,filter};
  if(previous){const end=ctx.currentTime+(reduced?.15:1.8);previous.gain.gain.cancelScheduledValues(ctx.currentTime);previous.gain.gain.setValueAtTime(previous.gain.gain.value,ctx.currentTime);previous.gain.gain.linearRampToValueAtTime(0,end);previous.oscillators.forEach(node=>node.stop(end+.05));}
 }
 async function toggleSound(){if(!audio.current)audio.current=new AudioContext();if(sound){voice.current?.gain.gain.setTargetAtTime(0,audio.current.currentTime,.08);await audio.current.suspend();setSound(false);return;}await audio.current.resume();startRoomVoice(room,true);setSound(true);}
 useEffect(()=>{if(sound&&audio.current&&audio.current.state==='running')startRoomVoice(room);},[room]);
 function advance(delta:number){if(focus){const siblings=artworks.filter(a=>a.room===focus.room),i=siblings.findIndex(a=>a.id===focus.id);inspect(siblings[(i+delta+siblings.length)%siblings.length]);}else {setViewVersion(v=>v+1);const next=Math.max(0,Math.min(page+delta,pages-1));setPage(next);setDialogue(null);setActiveArtwork('');route(`room=${room}&wall=${next}`);}}
 return <main className={`museum-app ${fallback?'museum-fallback':''} phase-${phase}`}>
   <div className="museum-transition" key={viewVersion} aria-hidden="true"/><div className="museum-canvas" ref={host} aria-hidden="true"/>{(phase==='outside'||phase==='approach')&&<div className="museum-exterior-photo" aria-hidden="true"><Image src="/museum/exterior.webp" alt="" fill priority sizes="100vw"/></div>}
   {fallback&&<div className={`museum-flat room-${room}`}><Image src="/museum/exterior.webp" alt="" fill sizes="100vw" loading="lazy"/><div className="museum-flat-shade"/>{phase==='inside'&&guide&&<Image className="fallback-room-owner" src="/museum/owner-small.webp" alt="RayCat, owner of the Museum" width={160} height={192} loading="lazy"/>} {phase==='inside'&&<div className="museum-flat-wall">{(room==='hall'?artworks.filter(a=>[1,8,20].includes(a.order)):list.slice(page*6,page*6+6)).map(a=><button key={a.id} className={`flat-art ${a.displayType}`} onFocus={()=>tell(a.id)} onMouseEnter={()=>tell(a.id)} onMouseLeave={()=>{if(!stateRef.current.focus)setDialogue(null);}} onClick={()=>inspect(a)}><ArtworkImage key={a.id} src={a.roomSrc} alt={a.title} width={a.width} height={a.height}/><span>{a.title}</span></button>)}</div>}</div>}
   {!ready&&<div className="museum-loading" role="status" aria-live="polite"><span>THE RAYCAT MUSEUM</span><p>Opening the house…</p></div>}
   
   {(phase==='outside'||phase==='approach'||phase==='welcome')&&<button className="museum-skip" disabled={!ready} onClick={()=>visit('hall')}>SKIP INTRO</button>}{phase==='welcome'&&<>{fallback&&<div className="museum-owner-fallback"><Image src="/museum/owner-small.webp" alt="RayCat, the mansion owner, inviting you inside" width={384} height={461} loading="lazy"/></div>}<div className="museum-welcome"><p>Welcome home.</p></div></>}
   <div className="museum-top"><a href="/" aria-label="Exit Museum">← EXIT</a>{phase==='inside'&&<><button aria-expanded={menu==='rooms'} aria-controls="museum-panel" onClick={()=>setMenu(menu==='rooms'?'':'rooms')}>ROOMS</button><button aria-expanded={menu==='collection'} aria-controls="museum-panel" onClick={()=>setMenu(menu==='collection'?'':'collection')}>COLLECTION</button></>}<span className="museum-spacer"/>{phase==='inside'&&<button aria-pressed={guide} onClick={()=>{setGuide(v=>!v);setDialogue(null);}}>GUIDE: {guide?'ON':'OFF'}</button>}<button onClick={toggleSound}>{sound?'SOUND OFF':'SOUND ON'}</button><button aria-expanded={menu==='settings'} aria-controls="museum-panel" onClick={()=>setMenu(menu==='settings'?'':'settings')}>SETTINGS</button></div>
   {phase==='inside'&&<><div className="museum-room-title"><p>{room==='secret'?'THE SECRET TREASURY':rooms.find(r=>r.id===room)?.name}</p><span>{room==='secret'?'Some things were never meant to be catalogued.':rooms.find(r=>r.id===room)?.subtitle}</span></div>
   {room==='hall'&&<div className="museum-destinations">{rooms.slice(1).map(r=><button key={r.id} onPointerEnter={()=>prefetchWall(r.id)} onFocus={()=>prefetchWall(r.id)} onClick={()=>visit(r.id)}>{r.name} <span>↗</span></button>)}<button onClick={()=>setSecret(s=>s+1)} aria-label="Inspect RayCat portrait">The owner’s portrait</button><button onClick={()=>setNotice('NOT YET.')}>Locked wing</button></div>}
   <Navigation room={room} page={page} pages={pages} seen={seen.length} total={artworks.length} list={list} onRoom={visit} onWall={advance} onArt={inspect} onReset={()=>{engine.current?.reset();setNotice('VIEW RESET');}}/><p className="museum-hint">{fallback?'Select an artwork to inspect':mode==='guided'?'Choose a room below · scroll to approach · drag horizontally for 360°':'WASD to move · drag horizontally for 360° · select an artwork'}</p></>}
   {dialogue&&guide&&!menu&&!focus&&<RayCatDialogue key={dialogue.id} text={dialogue.guide!.story} reduced={reduced} onClose={()=>setDialogue(null)}/>}
   {notice&&<p className="museum-notice" role="status">{notice}</p>}
   {menu&&<button className="museum-panel-scrim" aria-label="Dismiss navigation" onClick={()=>setMenu('')}/>}{menu&&<aside ref={panel} id="museum-panel" role="dialog" aria-modal="true" className="museum-panel" aria-label={menu}><div className="museum-panel-heading"><h2>{menu}</h2><button onClick={()=>setMenu('')} aria-label="Close panel">✕</button></div>{menu==='rooms'&&rooms.map(r=><button className="museum-index-row" key={r.id} onClick={()=>visit(r.id)}>{r.name}<span>{r.id==='hall'?'↗':artworks.filter(a=>a.room===r.id).length}</span></button>)}{menu==='collection'&&<><label className="museum-search">Find a sighting<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Title or catalog number"/></label><div className="museum-catalog">{!artworks.some(a=>(a.title+' '+a.id).toLowerCase().includes(search.toLowerCase()))&&<p role="status">No sightings found. Try a title or catalog number.</p>}{artworks.filter(a=>(a.title+' '+a.id).toLowerCase().includes(search.toLowerCase())).map(a=><button className="museum-index-row" key={a.id} onClick={()=>inspect(a)}><span className="catalog-number">{a.id}</span><span>{a.title}<small>{a.medium}</small></span><span>↗</span></button>)}</div></>}{menu==='settings'&&<><label>NAVIGATION<select value={mode} onChange={e=>setMode(e.target.value)}><option value="guided">Guided · scroll and tap</option><option value="explore">Explore · WASD and drag</option></select></label><label>QUALITY<select value={quality} onChange={e=>setQuality(e.target.value)}>{['auto','low','standard','cinematic'].map(q=><option key={q}>{q}</option>)}</select></label><label>EXPERIENCE<select value={fallback?'2d':'3d'} onChange={e=>setFallback(e.target.value==='2d')}><option value="3d">Spatial museum</option><option value="2d">Accessible 2D museum</option></select></label><p>Sound begins muted. Motion follows your device preference.</p></>}</aside>}
   <dialog aria-labelledby="museum-art-title" className="museum-focus" ref={dialog} onCancel={e=>{e.preventDefault();closeFocus();}} onKeyDown={e=>{if(e.key==='ArrowRight')advance(1);if(e.key==='ArrowLeft')advance(-1);}}>{focus&&<><div className="focus-top"><span>{focus.id} / THE RAYCAT MUSEUM</span><button onClick={closeFocus} autoFocus>CLOSE ✕</button></div><div className="focus-image"><ArtworkImage key={focus.id} src={focus.focusSrc} preview={focus.roomSrc} alt={focus.title} fill/></div><div className="focus-details">{guide&&dialogue?.id===focus.id&&focus.guide&&<RayCatDialogue key={focus.id} text={focus.guide.story} reduced={reduced} onClose={()=>setDialogue(null)}/>}<div><h2 id="museum-art-title">{focus.title}</h2><p>DATE UNKNOWN · {focus.medium}</p></div><div><button onClick={()=>advance(-1)}>← PREVIOUS</button><button onClick={()=>{setPage(Math.floor(artworks.filter(a=>a.room===focus.room).findIndex(a=>a.id===focus.id)/6));closeFocus();}}>VIEW IN ROOM</button><button onClick={()=>advance(1)}>NEXT →</button></div></div></>}</dialog>
 </main>;
}

import "./entry.css";

import "./welcome.css";

import "./guide-presence.css";
