'use client';
import RayCatDialogue from './RayCatDialogue';
import './guide.css';

import {useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import Navigation from './Navigation';
import './navigation.css';
import {artworks,rooms,Artwork,MuseumState} from './model';
import './museum.css';

export default function Museum(){
 const host=useRef<HTMLDivElement>(null),engine=useRef<ReturnType<typeof import('./engine').createMuseum>|null>(null),dialog=useRef<HTMLDialogElement>(null),audio=useRef<AudioContext|null>(null);
 const [room,setRoom]=useState('hall'),[phase,setPhase]=useState('outside'),[mode,setMode]=useState('guided'),[quality,setQuality]=useState('auto'),[reduced,setReduced]=useState(false),[fallback,setFallback]=useState(false),[ready,setReady]=useState(false),[page,setPage]=useState(0),[focus,setFocus]=useState<Artwork|null>(null),[menu,setMenu]=useState(''),[search,setSearch]=useState(''),[seen,setSeen]=useState<string[]>([]),[sound,setSound]=useState(false),[secret,setSecret]=useState(0),[notice,setNotice]=useState('');
 const [guide,setGuide]=useState(true),[dialogue,setDialogue]=useState<Artwork|null>(null);const spoken=useRef(new Set<string>());
 function tell(id:string){const art=artworks.find(a=>a.id===id);if(!guide||!art?.guide||spoken.current.has(id))return;spoken.current.add(id);setDialogue(art);}
 const [viewVersion,setViewVersion]=useState(0);
 const list=room==='secret'?artworks.filter(a=>[20,49,50].includes(a.order)):artworks.filter(a=>a.room===room);const pages=Math.max(1,Math.ceil(list.length/6));
 const state:MuseumState={guide,room,phase,mode,quality,reduced,focus:!!focus||!!menu,page};const stateRef=useRef(state);stateRef.current=state;
 const actions=useRef<(kind:string,id:string)=>void>(()=>{});
 function visit(id:string){setDialogue(null);setViewVersion(v=>v+1);setRoom(id);setPage(0);setPhase('inside');setMenu('');setFocus(null);history.replaceState(null,'',`/museum?room=${id}`);}
 function inspect(art:Artwork){setRoom(art.room);setPhase('inside');setFocus(art);setPage(Math.floor(artworks.filter(a=>a.room===art.room).findIndex(a=>a.id===art.id)/6));setSeen(s=>s.includes(art.id)?s:[...s,art.id]);setMenu('');history.replaceState(null,'',`/museum?art=${art.id}`);}
 function closeFocus(){setFocus(null);history.replaceState(null,'',`/museum?room=${room}`);}
 actions.current=(kind,id)=>{if(kind==='guide')tell(id);if(kind==='guide-leave')setDialogue(null);if(kind==='art'){tell(id);const a=artworks.find(a=>a.id===id);if(a)inspect(a);}if(kind==='room')visit(id);if(kind==='secret')setSecret(s=>s+1);if(kind==='locked')setNotice('NOT YET.');if(kind==='drawer')setPage(p=>(p+1)%pages);if(kind==='wheel')setNotice('THE MECHANISM WAKES.');};
 useEffect(()=>{const mq=matchMedia('(prefers-reduced-motion: reduce)');setReduced(mq.matches);const change=()=>setReduced(mq.matches);mq.addEventListener('change',change);const params=new URLSearchParams(location.search);const art=artworks.find(a=>a.id===params.get('art'));if(art)inspect(art);else if(rooms.some(r=>r.id===params.get('room')))visit(params.get('room')!);if(params.get('fallback')==='1')setFallback(true);const saved=sessionStorage.getItem('raycat-museum-seen');if(saved){try{const ids=JSON.parse(saved);if(Array.isArray(ids))setSeen(ids.filter(id=>artworks.some(a=>a.id===id)));}catch{}}return()=>mq.removeEventListener('change',change);},[]);
 useEffect(()=>{if(fallback){setReady(true);return;}let cancelled=false;import('./engine').then(({createMuseum})=>{if(cancelled||!host.current)return;try{engine.current=createMuseum(host.current,stateRef.current,(k,id)=>actions.current(k,id),()=>setFallback(true));setReady(true);}catch{setFallback(true);setReady(true);}}).catch(()=>{setFallback(true);setReady(true)});return()=>{cancelled=true;engine.current?.dispose();engine.current=null;};},[fallback]);
 useEffect(()=>{engine.current?.update(state);},[room,phase,mode,quality,reduced,focus,menu,page,guide]);
 useEffect(()=>{if(ready&&phase==='outside'){const timer=setTimeout(()=>setPhase('approach'),reduced?100:650);return()=>clearTimeout(timer);}},[ready,phase,reduced]);
 useEffect(()=>{if(phase==='inside'){try{localStorage.setItem('raycat-intro-complete','1');}catch{}}},[phase]);
 useEffect(()=>{if(phase==='approach'){const t=setTimeout(()=>setPhase('welcome'),reduced?100:5200);return()=>clearTimeout(t);}if(phase==='welcome'){const t=setTimeout(()=>setPhase('inside'),reduced?3200:7000);return()=>clearTimeout(t);}},[phase,reduced]);
 useEffect(()=>{if(secret>=3){visit('secret');setNotice('THE HOUSE REMEMBERS.');setSecret(0);}},[secret]);
 useEffect(()=>{if(notice){const t=setTimeout(()=>setNotice(''),2800);return()=>clearTimeout(t);}},[notice]);
 useEffect(()=>{if(focus&&!dialog.current?.open)dialog.current?.showModal();if(!focus&&dialog.current?.open)dialog.current.close();},[focus]);
 useEffect(()=>()=>{audio.current?.close();},[]);
 useEffect(()=>{if(seen.length)sessionStorage.setItem('raycat-museum-seen',JSON.stringify(seen));},[seen]);
 useEffect(()=>{const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setMenu('');};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape);},[]);
 async function toggleSound(){if(!audio.current){const ctx=new AudioContext();audio.current=ctx;const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sine';osc.frequency.value=58;gain.gain.value=.018;osc.connect(gain);gain.connect(ctx.destination);osc.start();}if(sound)await audio.current.suspend();else await audio.current.resume();setSound(!sound);}
 function advance(delta:number){if(focus){const siblings=artworks.filter(a=>a.room===focus.room),i=siblings.findIndex(a=>a.id===focus.id);inspect(siblings[(i+delta+siblings.length)%siblings.length]);}else {setViewVersion(v=>v+1);setPage(p=>Math.max(0,Math.min(p+delta,pages-1)));}}
 return <main className={`museum-app ${fallback?'museum-fallback':''} phase-${phase}`}>
   <div className="museum-transition" key={viewVersion} aria-hidden="true"/><div className="museum-canvas" ref={host} aria-label="Interactive museum architecture"/>{(phase==='outside'||phase==='approach')&&<div className="museum-exterior-photo" aria-hidden="true"><Image src="/museum/exterior.webp" alt="" fill priority sizes="100vw"/></div>}
   {fallback&&<div className={`museum-flat room-${room}`}><Image src="/museum/exterior.webp" alt="" fill sizes="100vw" priority/><div className="museum-flat-shade"/>{phase==='inside'&&guide&&<Image className="fallback-room-owner" src="/museum/owner-small.webp" alt="RayCat, owner of the Museum" width={160} height={192}/>} {phase==='inside'&&<div className="museum-flat-wall">{(room==='hall'?artworks.filter(a=>[1,8,20].includes(a.order)):list.slice(page*6,page*6+6)).map(a=><button key={a.id} className={`flat-art ${a.displayType}`} onFocus={()=>tell(a.id)} onMouseEnter={()=>tell(a.id)} onMouseLeave={()=>setDialogue(null)} onClick={()=>inspect(a)}><Image src={a.roomSrc} alt={a.title} width={a.width} height={a.height} sizes="(max-width:800px) 70vw, 25vw"/><span>{a.title}</span></button>)}</div>}</div>}
   {!ready&&<div className="museum-loading"><span>THE RAYCAT MUSEUM</span><p>Opening the house…</p></div>}
   
   {(phase==='outside'||phase==='approach'||phase==='welcome')&&<button className="museum-skip" onClick={()=>visit('hall')}>SKIP INTRO</button>}{phase==='welcome'&&<>{fallback&&<div className="museum-owner-fallback"><Image src="/museum/owner-small.webp" alt="RayCat, the mansion owner, inviting you inside" width={384} height={461}/></div>}<div className="museum-welcome"><p>Welcome home.</p></div></>}
   <div className="museum-top"><a href="/" aria-label="Exit Museum">← EXIT</a>{phase==='inside'&&<><button onClick={()=>setMenu(menu==='rooms'?'':'rooms')}>ROOMS</button><button onClick={()=>setMenu(menu==='collection'?'':'collection')}>COLLECTION</button></>}<span className="museum-spacer"/>{phase==='inside'&&<button aria-pressed={guide} onClick={()=>{setGuide(v=>!v);setDialogue(null);}}>GUIDE: {guide?'ON':'OFF'}</button>}<button onClick={toggleSound}>{sound?'SOUND OFF':'SOUND ON'}</button><button onClick={()=>setMenu(menu==='settings'?'':'settings')}>SETTINGS</button></div>
   {phase==='inside'&&<><div className="museum-room-title"><p>{room==='secret'?'THE SECRET TREASURY':rooms.find(r=>r.id===room)?.name}</p><span>{room==='secret'?'Some things were never meant to be catalogued.':rooms.find(r=>r.id===room)?.subtitle}</span></div>
   {room==='hall'&&<div className="museum-destinations">{rooms.slice(1).map(r=><button key={r.id} onClick={()=>visit(r.id)}>{r.name} <span>↗</span></button>)}<button onClick={()=>setSecret(s=>s+1)} aria-label="Inspect RayCat portrait">The owner’s portrait</button><button onClick={()=>setNotice('NOT YET.')}>Locked wing</button></div>}
   <Navigation room={room} page={page} pages={pages} seen={seen.length} total={artworks.length} list={list} onRoom={visit} onWall={advance} onArt={inspect} onReset={()=>{engine.current?.reset();setNotice('VIEW RESET');}}/><p className="museum-hint">{fallback?'Select an artwork to inspect':mode==='guided'?'Choose a room below · scroll to approach · drag to look':'WASD to move · drag to look · select an artwork'}</p></>}
   {dialogue&&guide&&!menu&&!focus&&<RayCatDialogue key={dialogue.id} text={dialogue.guide!.story} reduced={reduced} onClose={()=>setDialogue(null)}/>}
   {notice&&<p className="museum-notice" role="status">{notice}</p>}
   {menu&&<button className="museum-panel-scrim" aria-label="Dismiss navigation" onClick={()=>setMenu('')}/>}{menu&&<aside className="museum-panel" aria-label={menu}><div className="museum-panel-heading"><h2>{menu}</h2><button onClick={()=>setMenu('')} aria-label="Close panel">✕</button></div>{menu==='rooms'&&rooms.map(r=><button className="museum-index-row" key={r.id} onClick={()=>visit(r.id)}>{r.name}<span>{r.id==='hall'?'↗':artworks.filter(a=>a.room===r.id).length}</span></button>)}{menu==='collection'&&<><label className="museum-search">Find a sighting<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Title or catalog number"/></label><div className="museum-catalog">{artworks.filter(a=>(a.title+' '+a.id).toLowerCase().includes(search.toLowerCase())).map(a=><button className="museum-index-row" key={a.id} onClick={()=>inspect(a)}><span className="catalog-number">{a.id}</span><span>{a.title}<small>{a.medium}</small></span><span>↗</span></button>)}</div></>}{menu==='settings'&&<><label>NAVIGATION<select value={mode} onChange={e=>setMode(e.target.value)}><option value="guided">Guided · scroll and tap</option><option value="explore">Explore · WASD and drag</option></select></label><label>QUALITY<select value={quality} onChange={e=>setQuality(e.target.value)}>{['auto','low','standard','cinematic'].map(q=><option key={q}>{q}</option>)}</select></label><label>EXPERIENCE<select value={fallback?'2d':'3d'} onChange={e=>setFallback(e.target.value==='2d')}><option value="3d">Spatial museum</option><option value="2d">Accessible 2D museum</option></select></label><p>Sound begins muted. Motion follows your device preference.</p></>}</aside>}
   <dialog className="museum-focus" ref={dialog} onCancel={e=>{e.preventDefault();closeFocus();}} onKeyDown={e=>{if(e.key==='ArrowRight')advance(1);if(e.key==='ArrowLeft')advance(-1);}}>{focus&&<><div className="focus-top"><span>{focus.id} / THE RAYCAT MUSEUM</span><button onClick={closeFocus} autoFocus>CLOSE ✕</button></div><div className="focus-image"><Image src={focus.src} alt={focus.title} fill sizes="100vw" quality={95}/></div><div className="focus-details">{guide&&dialogue?.id===focus.id&&focus.guide&&<RayCatDialogue key={focus.id} text={focus.guide.story} reduced={reduced} onClose={()=>setDialogue(null)}/>}<div><h2>{focus.title}</h2><p>DATE UNKNOWN · {focus.medium}</p></div><div><button onClick={()=>advance(-1)}>← PREVIOUS</button><button onClick={()=>{setPage(Math.floor(artworks.filter(a=>a.room===focus.room).findIndex(a=>a.id===focus.id)/6));closeFocus();}}>VIEW IN ROOM</button><button onClick={()=>advance(1)}>NEXT →</button></div></div></>}</dialog>
 </main>;
}

import "./entry.css";

import "./welcome.css";

import "./guide-presence.css";
